// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ask': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ask.post').default>>>>
    }
    '/api/brain': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/brain.get').default>>>>
    }
    '/api/calendar': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calendar.get').default>>>>
    }
    '/api/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/config.get').default>>>>
    }
    '/api/finance': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/finance.get').default>>>>
    }
    '/api/inbox': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox.post').default>>>>
    }
    '/api/kickstart': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kickstart.post').default>>>>
    }
    '/api/mail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mail.get').default>>>>
    }
    '/api/metrics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/metrics.get').default>>>>
    }
    '/api/modules': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/modules.get').default>>>>
    }
    '/api/system': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system.get').default>>>>
    }
    '/api/tasks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}